# Evolution params
evolution_params:
  n_generations: 100
  population_size: 100
  remove_population_pct: 0.8
  n_elites: 0
  mutation_rate: 0.8
  mutation_factor: 0.1
  save_path: mnist/results/test
  seed_dir: null

# Prescriptor-specific params
prescriptor_params:
  model_params:
    activation: tanh
    in_size: 128
    hidden_sizes: [16]
    out_size: 1
  device: cuda:0

# Evaluation params
eval_params:
  device: cuda:0
  batch_size: 1024
  predictor_params:
    save_path: mnist/results/test/predictor.pt
    epochs: 10
    batch_size: 32
    conv_params:
      conv_blocks:
        - in_channels: 1
          out_channels: 16
          kernel_size: 5
          stride: 2
        - in_channels: 16
          out_channels: 32
          kernel_size: 3
          stride: 2
    decoder_params:
      activation: relu
      in_size: 129
      hidden_sizes: [16]
      out_size: 1